tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'caskroom/drivers'
tap 'universal-ctags/universal-ctags'

cask_args appdir: '/Applications'

# Basic tools

brew 'ack'
brew 'aria2'
brew 'gnupg2'
brew 'md5deep'
brew 'minicom'
brew 'mtr'
brew 'ncurses'
brew 'p7zip'
brew 'pstree'
brew 'pv'
brew 'rlwrap'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'unrar'
brew 'htop-osx'
brew 'zsh'
brew 'zsh-completions'
brew 'dos2unix'
brew 'fzf'
brew 'mutt'
brew 'ispell' # for emacs spelling support

# Network tools

brew 'arp-scan'
brew 'iftop'
brew 'arping'
brew 'tcpflow'

# Languagges

brew 'erlang'
brew 'elixir'
brew 'elm'
brew 'elm-format'
brew 'go'
brew 'leiningen'
brew 'lua'
brew 'chruby'
brew 'ruby-install'
brew 'yarn'
brew 'rust'
brew 'bashdb'
brew 'scala'
brew 'sbt' # scala build tools
brew 'python2'
brew 'python3'

# tools

brew 'direnv'
brew 'editorconfig'
brew 'emacs'
brew 'neovim'
brew 'tmate'
brew 'tmux'
brew 'the_silver_searcher'
brew 'terminal-notifier'
brew 'reattach-to-user-namespace'

# Admin trools

brew 'kubernetes-cli'
brew 's3cmd'
brew 'terraform'
brew 'awscli'
brew 'dehydrated'
brew 'certbot'
brew 'mas'
brew 'unison' #  File synchronization tool for OSX
cask 'launchcontrol'
cask "kitematic"

# Dev tools

brew 'git'
brew 'tig'
brew 'heroku'
brew 'postgresql'
brew 'universal-ctags', args: ['HEAD']
brew 'graphviz'
brew 'imagemagick'
brew 'grc' # colorise stdout with patterns
brew 'zmq'
brew "jq" # command-line JSON processor
brew "mosh" # mobile shell

# taskwarrior setup
brew 'task', args: ['HEAD']
brew 'timewarrior'
brew 'tasksh'
brew 'vit'

# Data tools

cask 'anaconda'
cask 'r-app'
cask 'rstudio'

# Everuyday Apps

# XXX cask 'google-chrome'
cask 'vlc'
cask 'alfred'
cask 'mailplane'
#cask '1password6'
cask 'bartender'
cask 'dropbox'
cask 'iina' # media player


# Dev Apps

cask 'hammerspoon'
cask 'iterm2'
cask 'dash'
cask 'slack'
cask 'virtualbox'
cask 'docker-edge'
cask 'vagrant'
cask 'synergy' # share keyboard/mouse b/w computers
cask 'balsamiq-mockups'
cask 'zerotier-one' # virtual networks
cask 'rcenvironment' # ENV variables pref pane
cask 'hazel' # file automation
cask 'kap' # screen to gif recorder
cask 'postman' # HTTP request tool
cask 'pingplotter' # ping grphing utility
cask 'java8'
cask 'github'
# XXX cask 'tunnelblick' # VPN
cask 'colloquy' # IRC client
cask 'sequel-pro'
cask 'gpg-suite'


# Personal Apps

# cask 'arq'
# cask 'crashplan'
# cask 'kindle'
# cask 'plex-media-server'
# cask 'plex-media-player'
# cask 'handbrake'
# cask 'viber'
# cask 'skype'
# cask 'whatsapp'
# cask 'torbrowser'
# cask 'fritzing'
# cask 'evernote'
# cask 'minecraft'
# cask 'sonos'
# cask 'telegram'

# cask 'anki' # flash xards


# FOR XING
brew 'ossp-uuid' # for XING
brew 'mysql' # for XING


# FOR KLARNA

brew 'pyenv-virtualenv'
brew "riemann"
brew "riemann-client"

brew "ditaa"  # ascii diagrams processor
# vim: ft=ruby
